# Use latest artnaseef/jboss-fuse-6.3 image as the base
FROM artnaseef/jboss-fuse-6.3

MAINTAINER Arthur Naseef <artnaseef@apache.org>

# Copy the users properties to enable the console
COPY users.properties /opt/jboss/jboss-fuse/etc/
